# -*- coding: utf-8 -*-
"""VGG16 ModelAge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uf1p3C8cs4GNJOtY86-KaybznZ31rJZ6
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import cv2
from keras.models import Sequential,load_model,Model
from keras.layers import Conv2D,MaxPool2D,Dense,Dropout,BatchNormalization,Flatten,Input
from sklearn.model_selection import train_test_split
from tqdm import tqdm  # for the progress bar
from google.colab import drive
import zipfile

# mounting google drive
drive.mount('/content/drive')

# path to the zip file
zip_path = '/content/drive/MyDrive/archive.zip'
extract_path = '/content/UTKFace'

# extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

def load_images_from_folder(folder, img_size=(128, 128)):
    images = [] #empty list to append the data to them
    ages = []

    # listing all the files in the folder
    file_list = os.listdir(folder)

    for img_name in tqdm(file_list):  #for progress bar
        age = int(img_name.split("_")[0]) # since the age is the data we need spliting it from the first index by delimeter
        img_path = os.path.join(folder, img_name)
        img = cv2.imread(img_path) #reading the image
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) #RGB 3 chanels
        img = cv2.resize(img, img_size) #resizing the image 128 , 128
        img = img / 255.0  # Scaling the images in a range 0 and 1
        images.append(img) #appending it to the empty list of the images list
        ages.append(age) # same for the age

    return np.array(images), np.array(ages) # returning them as numpy array [matrix of scaled image]

# Path to the extracted folder
folder_path = '/content/UTKFace/utkface_aligned_cropped/UTKFace'

# Load images and ages
images, ages = load_images_from_folder(folder_path)

#spliting the dataset into train and test
x_train, x_test, y_train, y_test = train_test_split(images, ages, test_size=0.15, random_state=42)

x_train[1]

x_test[1]

x_train.shape

x_test.shape

#the age distribution
plt.hist(y_train, bins=20, color='red', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Amount of samples')
plt.grid(True)
plt.show()

#a function to display images with their corresponding ages
def show_samples(images, ages, num_samples=5):
    fig, axes = plt.subplots(1, num_samples, figsize=(15, 15))
    for i in range(num_samples):
        axes[i].imshow(images[i])
        axes[i].set_title("Age: {}".format(ages[i]))
        axes[i].axis('off')
    plt.show()

# show some samples from the training set using the function created
show_samples(x_train, y_train)

from keras.applications import VGG16
# Load the VGG16 model with pretrained ImageNet weights
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(128, 128, 3))

# Freeze the layers of VGG16 model
for layer in base_model.layers:
    layer.trainable = False

# Create the model
age_model = Sequential()
age_model.add(base_model)

# Adding custom layers on top of VGG16
age_model.add(Flatten())
age_model.add(Dense(512, activation='relu'))
age_model.add(Dropout(0.5))
age_model.add(Dense(256, activation='relu'))
age_model.add(Dropout(0.5))
age_model.add(Dense(1, activation='relu', name='age'))

from keras.optimizers import Adam
age_model.compile(optimizer=Adam(learning_rate=0.0001), loss='mae', metrics=['mae'])

from tensorflow.keras.utils import plot_model
plot_model(age_model)

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

# call back function to stop the training once the model is over fitting when the val_loss after patience of 5 epochs will stop the training
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

#training the model

history_age = age_model.fit(x_train , y_train, validation_data=(x_test, y_test), epochs=50 , shuffle = True, batch_size = 32,callbacks=[early_stop])

import matplotlib.pyplot as plt
# Plot the training and validation loss
loss = history_age.history['loss']
val_loss = history_age.history['val_loss']
epochs = range(1, len(loss) + 1)
plt.plot(epochs, loss, 'y', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

test_loss, test_mae = age_model.evaluate(x_test, y_test)
print(f"Test Loss: {test_loss}")
print(f"Test MAE: {test_mae}")

index = 15
# get the original age (actual value)
original_age = y_train[index]
print("Original Age:", original_age)

# predict the age using the model
pred_age = age_model.predict(x_train[index].reshape(1, 128, 128, 3))[0][0]
print("Predicted Age:", pred_age)

# display the image
plt.imshow(x_train[index])
plt.title("Original Image")
plt.axis('off')
plt.show()

index = 30
# get the original age (actual value)
original_age = y_train[index]
print("Original Age:", original_age)

# predict the age using the model
pred_age = age_model.predict(x_train[index].reshape(1, 128, 128, 3))[0][0]
print("Predicted Age:", pred_age)

# display the image
plt.imshow(x_train[index])
plt.title("Original Image")
plt.axis('off')
plt.show()

age_model.save("/content/drive/MyDrive/TrainedCNN_model.h5")