# -*- coding: utf-8 -*-
"""Activation functions in NN without tensforflow and keras libaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6_vjJMkuF2k9dTJ71CYOMpLkmehmUoP
"""

import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

sigmoid(100)

sigmoid(50)

sigmoid(5)

sigmoid(1)

sigmoid(-2)

sigmoid(.5)

def tanh(x):
  return (math.exp(x)-math.exp(-x) / (math.exp(x)+ math.exp(-x)))

tanh(55)

def relu(x):
    return max(0,x)

relu(-15)

relu(5)

def leaky_relu(x):
    return max(0.1*x,x)

leaky_relu(-55)

leaky_relu(55)