# -*- coding: utf-8 -*-
"""Matrix minpulation in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XyLtbpzeGYz1NVImF_qj2X0vCqVgP3NK
"""

import numpy as np

revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

profit = revenue - expenses
profit

price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

#Numpy brodacsting it did as if its a 3 rows
price_per_unit*units

np.dot(price_per_unit,units)

